Esta apresentação irá abordar os seguintes tópicos: 

* [1. Um pouco sobre os arquivos .fits](#1.-Um-pouco-sobre-os-arquivos-.fits)
* [2. O pacote Astropy](#2.-O-pacote-Astropy)
* [3. Abrindo um arquivo .fits](#3.-Abrindo-um-arquivo-.fits)
* [4. Exibindo o tipo de conteúdo armazenado dentro dos arquivos .fits](#4.-Exibindo-o-tipo-de-conteúdo-armazenado-dentro-dos-arquivos-.fits)
* [5. Exibir as informações contidas nos arquivos](#5.-Exibir-as-informações-contidas-nos-arquivos)
* [6. Filtrando as informações contidas no Header dos arquivos](#6.-Filtrando-as-informações-contidas-no-Header-dos-arquivos)
* [7. Editando o Header da imagem](#7.-Editando-o-Header-da-imagem)
* [8. Exibir a tabela de dados contida no arquivos 2.fits](#8.-Exibir-a-tabela-de-dados-contida-no-arquivo-2.fits)
* [9. Exibindo os espectros contidos no arquivo 2.fits](#9.-Exibindo-os-espectros-contidos-no-arquivo-2.fits)
* [10. Exibindo a imagem do campo com o catálogo sobreposto "via WCS"](#10.-Exibindo-a-imagem-do-campo-com-o-catálogo-sobreposto-"via-WCS")
* [11. Criando um arquivo .fits](#11.-Criando-um-arquivo-.fits)

In [1]:
%matplotlib inline                           
%config InlineBackend.figure_format='retina'       # Melhora a resolucao do plot
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import matplotlib.pylab as plt                     # Permite fazer plots utilizando o pacote matplotlib
plt.rcParams['figure.figsize'] = (18.0, 18.0)      # Determina o tamanho do plot dentro do ipython notebook
from astropy.io import fits, votable               # Permite carregar arquivos fits e votable
from astropy.table import Table                    # Permite carregar tabelas
from astropy import wcs                            # Importa o pacote World Coordinate System
import numpy as np         

In [2]:
#hdulist = fits.open('/home/usuario/Documents/Mestrado/FFIs/8_golden/tess/tess2019131073826-4-4-0016-s_ffic.fits')
hdulist2 = fits.open('/home/usuario/Documents/Mestrado/FFIs/kplr2009114174833_ffi-cal.fits')
hdulis3 = fits.open('/home/usuario/Documents/Mestrado/FFIs/8_golden/tess/tess2019.fits')

In [3]:
from astropy.nddata.utils import Cutout2D
data = np.arange(20.).reshape(5, 4)
cutout1 = Cutout2D(data, (2, 1), (3, 3))
print(cutout1.data)
data

[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 9. 10. 11.]]


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [18]:
ref,rhead = fits.getdata('/home/usuario/Documents/Mestrado/FFIs/8_golden/tess/tess2019.fits', header = True)
rhead

XTENSION= 'BINTABLE'           / marks the beginning of a new HDU               
BITPIX  =                    8 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                   77 / length of first array dimension                
NAXIS2  =                20610 / length of second array dimension               
PCOUNT  =                    0 / group parameter count (not used)               
GCOUNT  =                    1 / group count (not used)                         
TFIELDS =                   19 / number of table fields                         
TTYPE1  = 'TIME    '           / column title: data time stamps                 
TFORM1  = 'D       '           / column format: 64-bit floating point           
TUNIT1  = 'JD - 2457000, days' / column units: TESS modified Julian date (TJD)  
TDISP1  = 'D14.7   '           / column display format                          
TTYPE2  = 'CADENCENO'       

In [6]:
hdulist2.info()

Filename: /home/usuario/Documents/Mestrado/FFIs/kplr2009114174833_ffi-cal.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      57   ()      
  1  MOD.OUT 2.1    1 ImageHDU       100   (1132, 1070)   float32   
  2  MOD.OUT 2.2    1 ImageHDU       100   (1132, 1070)   float32   
  3  MOD.OUT 2.3    1 ImageHDU       100   (1132, 1070)   float32   
  4  MOD.OUT 2.4    1 ImageHDU       100   (1132, 1070)   float32   
  5  MOD.OUT 3.1    1 ImageHDU       100   (1132, 1070)   float32   
  6  MOD.OUT 3.2    1 ImageHDU       100   (1132, 1070)   float32   
  7  MOD.OUT 3.3    1 ImageHDU       100   (1132, 1070)   float32   
  8  MOD.OUT 3.4    1 ImageHDU       100   (1132, 1070)   float32   
  9  MOD.OUT 4.1    1 ImageHDU       100   (1132, 1070)   float32   
 10  MOD.OUT 4.2    1 ImageHDU       100   (1132, 1070)   float32   
 11  MOD.OUT 4.3    1 ImageHDU       100   (1132, 1070)   float32   
 12  MOD.OUT 4.4    1 ImageHDU       100   (1132,

In [4]:
header = hdulist[1].header
#header

In [5]:
hdulist[1].header

XTENSION= 'IMAGE   '           / marks the beginning of a new HDU               
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / NAXIS                                          
NAXIS1  =                 2136 / length of first array dimension                
NAXIS2  =                 2078 / length of second array dimension               
PCOUNT  =                    0 / group parameter count (not used)               
GCOUNT  =                    1 / group count (not used)                         
INHERIT =                    T / inherit the primary header                     
EXTNAME = 'CAMERA.CCD 4.4 cal' / name of extension                              
EXTVER  =                    1 / extension version number (not format version)  
TELESCOP= 'TESS    '           / telescope                                      
INSTRUME= 'TESS Photometer'    / detector type                                  
CAMERA  =                   

In [7]:
hdulist2[1].header


XTENSION= 'IMAGE   '           / marks the beginning of a new HDU               
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / NAXIS                                          
NAXIS1  =                 1132 / length of first array dimension                
NAXIS2  =                 1070 / length of second array dimension               
PCOUNT  =                    0 / group parameter count (not used)               
GCOUNT  =                    1 / group count (not used)                         
INHERIT =                    T / inherit the primary header                     
EXTNAME = 'MOD.OUT 2.1'        / name of extension                              
EXTVER  =                    1 / extension version number (not format version)  
TELESCOP= 'Kepler  '           / telescope                                      
INSTRUME= 'Kepler Photometer'  / detector type                                  
CHANNEL =                   